name: Build and Release ESPHome Firmware

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python and dependencies
        run: make setup

      - name: Build firmware
        run: make build

      - name: Create output directory
        run: mkdir -p firmwares && mv firmware.bin firmwares/

      - name: Upload firmware artifacts
        uses: actions/upload-artifact@v3
        with:
          name: firmware-binaries
          path: firmwares/

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download firmware artifacts
        uses: actions/download-artifact@v3
        with:
          name: firmware-binaries
          path: firmwares/

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: firmwares/*
